---
# Firewall handlers

- name: Restart ufw
  ansible.builtin.systemd:
    name: ufw
    state: restarted

- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
